% サブ関数、メインGUIのライブモードの前に実行します
sub_GetStatus
sub_GetChildDevice
sub_GetDeviceName
sub_GetMaxFrames
sub_GetRecordRate
sub_SetStatusLive
sub_GetColorType
sub_GetMaxResolution
sub_GetResolution
sub_GetShutterSpeedFps
sub_GetShadingMode
sub_SetTriggerMode_Start
if nRet == PDC_FAILED
    sub_SetTriggerMode_Center
end
sub_GetRecordRateList
sub_GetResolutionList
sub_GetShutterSpeedFpsList
sub_GetTransferOption
%JL011323 added sub_SetPartitionList
sub_SetPartitionList

nBitDepth = 8;

