%メインGUIのコールバックの設定

set(S.live_radio,'Callback',{@live_radio_Callback});
set(S.livestop_radio,'Callback',{@livestop_radio_Callback});
set(S.memory_radio,'Callback',{@memory_radio_Callback});
set(S.record_button,'Callback',{@record_button_Callback});
set(S.waiting_button,'Callback',{@waiting_button_Callback});
set(S.endless_button,'Callback',{@endless_button_Callback});
set(S.record_stop_button,'Callback',{@record_stop_button_Callback});
set(S.play_toggle_button,'Callback',{@play_toggle_button_Callback});
set(S.path_button,'Callback',{@path_button_Callback});
set(S.stop_button,'Callback',{@stop_button_Callback});
set(S.start_frame_edit,'Callback',{@start_frame_edit_Callback});
set(S.current_frame_edit,'Callback',{@current_frame_edit_Callback});
set(S.end_frame_edit,'Callback',{@end_frame_edit_Callback});
set(S.frame_slider,'Callback',{@frame_slider_Callback});
set(S.camera_toggle_button,'Callback',{@camera_toggle_button_Callback});
set(S.data_toggle_button,'Callback',{@data_toggle_button_Callback});
set(S.save_button,'Callback',{@save_button_Callback});
set(S.close_button,'Callback',{@close_button_Callback});
set(S.fh,'CloseRequestFcn',{@closeGUI});
set(S.recordrate_pop,'Callback',{@recordrate_pop_Callback});
set(S.shutter_pop,'Callback',@shutter_pop_Callback);
set(S.trigger_pop,'Callback',{@trigger_pop_Callback});
set(S.resolution_pop,'Callback',{@resolution_pop_Callback});
set(S.shading_pop,'Callback',{@shading_pop_Callback});
set(S.head_t1_pop,'Callback',{@head_t1_pop_Callback});
set(S.head_t2_pop,'Callback',{@head_t2_pop_Callback});
set(S.fh,'ResizeFcn',{@resizeGUI});