function convertMetaDataFile(oldMetaDataFile)

%This script is used to convert the metadta file generated by the flybowl 0 to the new format. 
%This way we are not changing the set up on the old flybowl, but still allowing for the option 
%for videos collected on this bowl to also be run on Alice’s pipeline.

%example 
% convertMetaDataFile('E:\Current Projects\FlyBowl4\metaDataFileConversion\metaDataOld.xml');
% it will generate a new format metafile, metaDataNew.xml, in the same folder

%Jinyang Liu
%07/18/2019

if exist(oldMetaDataFile)
    %step 1: read the metaData Xml file for the old flyBowl into a stucture
    [FILEPATH,~,~] = fileparts(oldMetaDataFile);
    oldData = xml2struct(oldMetaDataFile);
    
    %step 2: generat a new structure and modified the field value\
    newData = xml2struct('newMetaDataTemplate.xml');
    
    newData.experiment.Attributes.exp_datetime = oldData.flyBowl.Attributes.exp_datetime;
    newData.experiment.Attributes.experimenter = oldData.flyBowl.Attributes.experimenter;
    
    newData.experiment.session.apparatus.Attributes.rig = '0';
    newData.experiment.session.apparatus.Attributes.room = '3E.288';
    
    newData.experiment.session.flies.Attributes.cross_date = oldData.flyBowl.flies.Attributes.cross_date;
    newData.experiment.session.flies.Attributes.female_parent = oldData.flyBowl.flies.Attributes.female_parent;
    newData.experiment.session.flies.Attributes.male_parent = oldData.flyBowl.flies.Attributes.male_parent;
    newData.experiment.session.flies.Attributes.flip_used = oldData.flyBowl.flies.Attributes.flip_used;
    newData.experiment.session.flies.Attributes.num_flies = oldData.flyBowl.flies.Attributes. num_flies;
    newData.experiment.session.flies.Attributes.gender = oldData.flyBowl.flies.Attributes.gender;
    
    newData.experiment.session.flies.rearing.Attributes.rearing_incubator = oldData.flyBowl.flies.rearing.Attributes.incubator;
    
    
    newData.experiment.session.flies.handling.Attributes.datetime_sorted = oldData.flyBowl.flies.handling.Attributes.datetime_sorted;
    newData.experiment.session.flies.handling.Attributes.handler_cross = oldData.flyBowl.flies.handling.Attributes.handler_cross;
    newData.experiment.session.flies.handling.Attributes.handler_sorting = oldData.flyBowl.flies.handling.Attributes.handler_sorting;
    
    newData.experiment.environment.Attributes.IR_intensity = oldData.flyBowl.environment.Attributes.IR_intensity;
    newData.experiment.environment.Attributes.humidity = oldData.flyBowl.environment.Attributes.humidity;
    newData.experiment.environment.Attributes.temperature = oldData.flyBowl.environment.Attributes.temperature;
    
    % newData.data_capture_version = 'MingWu';
    % newData.screen_type='primary';
    % newData.apparatus_id='Rig1_Plate21_Bowl1_Camerab71f0b94a8d99e946d05dc2e4d5f2d36_ComputerFLYBOWL-WW3_HardDriveHD1';
    % newData.bowl=1;
    % newData.camera='b71f0b94a8d99e946d05dc2e4d5f2d36';
    % newData.computer='FLYBOWL-WW3';
    % newData.harddrive='HD1';
    % newData.top_plate=21;
    % newData.cross_barcode=-1;
    % newData.effector='UAS_dTrpA1_2_0002';
    % newData.line='duplicate_1xLwt_attp40_4stop1';
    % newData.rearing_protocol='protocolVer3_test.xlsx';
    % newData.handling_protocol='protocol_FeAg_KS.xlsx';
    % newData.led_protocol='protocolVer3_test.xlsx';
    % newData.protocol='protocolVer3_testfromEn1.xlsx';
    % newData.num_flies_dead=12;
    % newData.seconds_fliesloaded=279;
    % newData.flag_redo=0;
    % newData.flag_aborted=0;
    
    %step 3: save the new structure as a xml file
    newMetaDataFile = fullfile(FILEPATH,'metaDataNew.xml'); 
    struct2xml(newData, newMetaDataFile);
else
    disp('Cannot find old metaDataFile');
end

